import { ICountryList } from "./t";

export const c = [
  {
    n: "Afghanistan",
    c: "AFG",
    d: "+93",
    f: "+93 ## ########",
    p: "+93 70 14547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/af.png",
    c_sm: "AF",
  },
  {
    n: "Albania",
    c: "ALB",
    d: "+355",
    f: "+355 ### ### ####",
    p: "+355 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/al.png",
    c_sm: "AL",
  },
  {
    n: "Algeria",
    c: "DZA",
    d: "+213",
    f: "+213 ### ### ####",
    p: "+213 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/dz.png",
    c_sm: "DZ",
  },
  {
    n: "Andorra",
    c: "AND",
    d: "+376",
    f: "+376 ### ### ####",
    p: "+376 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ad.png",
    c_sm: "AD",
  },
  {
    n: "Angola",
    c: "AGO",
    d: "+244",
    f: "+244 ### ### ####",
    p: "+244 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ao.png",
    c_sm: "AO",
  },
  {
    n: "Antigua and barbuda",
    c: "ATG",
    d: "+1268",
    f: "+1268 ### ### ####",
    p: "+1268 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ag.png",
    c_sm: "AG",
  },
  {
    n: "Argentina",
    c: "ARG",
    d: "+54",
    f: "+54 (##) ########",
    p: "+54 (70) 14547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ar.png",
    c_sm: "AR",
  },
  {
    n: "Armenia",
    c: "ARM",
    d: "+374",
    f: "+374 ## ######",
    p: "+374 70 145477",
    fg: "http://flags.fmcdn.net/data/flags/mini/am.png",
    c_sm: "AM",
  },
  {
    n: "Aruba",
    c: "ABW",
    d: "+297",
    f: "+297 ### ### ####",
    p: "+297 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/aw.png",
    c_sm: "AW",
  },
  {
    n: "Australia",
    c: "AUS",
    d: "+61",
    f: "+61 (##) #### ####",
    p: "+61 (70) 1454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/au.png",
    c_sm: "AU",
  },
  {
    n: "Austria",
    c: "AUT",
    d: "+43",
    f: "+43 (###) ### ####",
    p: "+43 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/at.png",
    c_sm: "AT",
  },
  {
    n: "Azerbaijan",
    c: "AZE",
    d: "+994",
    f: "+994 (##) ### ## ##",
    p: "+994 (70) 145 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/az.png",
    c_sm: "AZ",
  },
  {
    n: "Bahamas",
    c: "BHS",
    d: "+994",
    f: "+1242 (###) ### ####",
    p: "+1242 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bs.png",
    c_sm: "BS",
  },
  {
    n: "Bahrain",
    c: "BHR",
    d: "+973",
    f: "+973 (###) ### ####",
    p: "+973 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bh.png",
    c_sm: "BH",
  },
  {
    n: "Bangladesh",
    c: "BGD",
    d: "+880",
    f: "+880 (###) ### ####",
    p: "+880 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bd.png",
    c_sm: "BD",
  },
  {
    n: "Barbados",
    c: "BRB",
    d: "+1246",
    f: "+1246 (###) ### ####",
    p: "+1246 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bb.png",
    c_sm: "BB",
  },
  {
    n: "Belarus",
    c: "BLR",
    d: "+375",
    f: "+375 (##) ### ## ##",
    p: "+375 (70) 145 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/by.png",
    c_sm: "BY",
  },
  {
    n: "Belgium",
    c: "BEL",
    d: "+32",
    f: "+32 ### ## ## ##",
    p: "+32 701 45 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/be.png",
    c_sm: "BE",
  },
  {
    n: "Belize",
    c: "BLZ",
    d: "+32",
    f: "+32 ### ### ####",
    p: "+32 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bz.png",
    c_sm: "BZ",
  },
  {
    n: "Benin",
    c: "BEN",
    d: "+229",
    f: "+229 ### ### ####",
    p: "+229 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bj.png",
    c_sm: "BJ",
  },
  {
    n: "Bhutan",
    c: "BTN",
    d: "+975",
    f: "+975 ### ### ####",
    p: "+975 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bt.png",
    c_sm: "BT",
  },
  {
    n: "Bolivia",
    c: "BOL",
    d: "+591",
    f: "+591 ### ### ####",
    p: "+591 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bo.png",
    c_sm: "BO",
  },
  {
    n: "Bosnia and herzegovina",
    c: "BES",
    d: "+387",
    f: "+387 ### ### ####",
    p: "+387 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ba.png",
    c_sm: "BA",
  },
  {
    n: "Botswana",
    c: "BWA",
    d: "+267",
    f: "+267 ### ### ####",
    p: "+267 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bw.png",
    c_sm: "BW",
  },
  {
    n: "Brazil",
    c: "BRA",
    d: "+55",
    f: "+55 (##) #########",
    p: "+55 (70) 145477333",
    fg: "http://flags.fmcdn.net/data/flags/mini/br.png",
    c_sm: "BR",
  },
  {
    n: "British indian ocean territory",
    c: "IOT",
    d: "+246",
    f: "+246 (###) ### ####",
    p: "+246 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/io.png",
    c_sm: "IO",
  },
  {
    n: "Brunei",
    c: "BRN",
    d: "+673",
    f: "+673 (###) ### ####",
    p: "+673 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bn.png",
    c_sm: "BN",
  },
  {
    n: "Bulgaria",
    c: "BGR",
    d: "+359",
    f: "+359 (###) ### ####",
    p: "+359 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bg.png",
    c_sm: "BG",
  },
  {
    n: "Burkina faso",
    c: "BFA",
    d: "+226",
    f: "+226 (###) ### ####",
    p: "+226 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bf.png",
    c_sm: "BF",
  },
  {
    n: "Burundi",
    c: "BDI",
    d: "+257",
    f: "+257 (###) ### ####",
    p: "+257 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bi.png",
    c_sm: "BI",
  },
  {
    n: "Cape Verde",
    c: "CPV",
    d: "+238",
    f: "+238 (###) ###-####",
    p: "+238 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cv.png",
    c_sm: "CV",
  },
  {
    n: "Cambodia",
    c: "KHM",
    d: "+855",
    f: "+855 (###) ### ####",
    p: "+855 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/kh.png",
    c_sm: "KH",
  },
  {
    n: "Cameroon",
    c: "CMR",
    d: "+237",
    f: "+237 (###) ### ####",
    p: "+237 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cm.png",
    c_sm: "CM",
  },
  {
    n: "Canada",
    c: "CAN",
    d: "+1",
    f: "+1 (###) ###-####",
    p: "+1 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ca.png",
    c_sm: "CA",
  },
  {
    n: "Caribbean netherlands",
    c: "BQ",
    d: "+599",
    f: "+599 (###) ###-####",
    p: "+599 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/bq.png",
    c_sm: "BQ",
  },
  {
    n: "Central african republic",
    c: "CAF",
    d: "+236",
    f: "+236 (###) ###-####",
    p: "+236 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cf.png",
    c_sm: "CF",
  },
  {
    n: "Chad",
    c: "TCD",
    d: "+235",
    f: "+235 (###) ###-####",
    p: "+235 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/td.png",
    c_sm: "TD",
  },
  {
    n: "Chile",
    c: "CHL",
    d: "+56",
    f: "+56 (###) ###-####",
    p: "+56 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cl.png",
    c_sm: "CL",
  },
  {
    n: "China",
    c: "CHN",
    d: "+86",
    f: "+86 ##-#########",
    p: "+86 70-145477333",
    fg: "http://flags.fmcdn.net/data/flags/mini/cn.png",
    c_sm: "CN",
  },
  {
    n: "Colombia",
    c: "COL",
    d: "+57",
    f: "+57 ### ### ####",
    p: "+57 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/co.png",
    c_sm: "CO",
  },
  {
    n: "Comoros",
    c: "COM",
    d: "+269",
    f: "+269 ### ### ####",
    p: "+269 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/km.png",
    c_sm: "KM",
  },
  {
    n: "Democratic Republic of the Congo",
    c: "COD",
    d: "+243",
    f: "+243 ### ### ####",
    p: "+243 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cd.png",
    c_sm: "CD",
  },
  {
    n: "Republic of the Congo",
    c: "COG",
    d: "+242",
    f: "+242 ### ### ####",
    p: "+242 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cg.png",
    c_sm: "CG",
  },
  {
    n: "Costa rica",
    c: "CRI",
    d: "+506",
    f: "+506 ####-####",
    p: "+506 7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/cr.png",
    c_sm: "CR",
  },
  {
    n: "Croatia",
    c: "HRV",
    d: "+385",
    f: "+385 ### ### ####",
    p: "+385 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/hr.png",
    c_sm: "HR",
  },
  {
    n: "Cuba",
    c: "CUB",
    d: "+53",
    f: "+53 ### ### ####",
    p: "+53 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cu.png",
    c_sm: "CU",
  },
  {
    n: "Curaçao",
    c: "CUW",
    d: "+599",
    f: "+599 (###) ### ####",
    p: "+599 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/cw.png",
    c_sm: "CW",
  },
  {
    n: "Cyprus",
    c: "CYP",
    d: "+357",
    f: "+357 ## ######",
    p: "+357 70 145477",
    fg: "http://flags.fmcdn.net/data/flags/mini/cy.png",
    c_sm: "cy",
  },
  {
    n: "Czech republic",
    c: "CZE",
    d: "+420",
    f: "+420 (###) ### ###",
    p: "+420 (701) 454 773",
    fg: "http://flags.fmcdn.net/data/flags/mini/cz.png",
    c_sm: "CZ",
  },
  {
    n: "Côte d’Ivoire",
    c: "CIV",
    d: "+225",
    f: "+225 ## ## ## ##",
    p: "+225 70 14 54 77",
    fg: "http://flags.fmcdn.net/data/flags/mini/ci.png",
    c_sm: "ci",
  },
  {
    n: "Denmark",
    c: "DNK",
    d: "+45",
    f: "+45 ## ## ## ##",
    p: "+45 70 14 54 77",
    fg: "http://flags.fmcdn.net/data/flags/mini/dk.png",
    c_sm: "DK",
  },
  {
    n: "Djibouti",
    c: "DJI",
    d: "+253",
    f: "+253 (###) ### ####",
    p: "+253 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/dj.png",
    c_sm: "DJ",
  },
  {
    n: "Dominica",
    c: "DMA",
    d: "+1767",
    f: "+1767 (###) ### ####",
    p: "+1767 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/dm.png",
    c_sm: "DM",
  },
  {
    n: "Dominican republic ",
    c: "DOM",
    d: "+1809",
    f: "+1809 (###) ### ####",
    p: "+1809 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/do.png",
    c_sm: "DO",
  },
  {
    n: "Dominican republic  ",
    c: "DOM",
    d: "+1829",
    f: "+1829 (###) ### ####",
    p: "+1829 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/do.png",
    c_sm: "DO",
  },
  {
    n: "Dominican republic   ",
    c: "DOM",
    d: "+1849",
    f: "+1849 (###) ### ####",
    p: "+1849 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/do.png",
    c_sm: "DO",
  },
  {
    n: "Ecuador",
    c: "ECU",
    d: "+593",
    f: "+593 (###) ### ####",
    p: "+593 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ec.png",
    c_sm: "EC",
  },
  {
    n: "Egypt",
    c: "EGY",
    d: "+20",
    f: "+20 ### ### ####",
    p: "+20 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/eg.png",
    c_sm: "EG",
  },
  {
    n: "El salvador",
    c: "SLV",
    d: "+503",
    f: "+503 ####-####",
    p: "+503 7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/sv.png",
    c_sm: "SV",
  },
  {
    n: "Equatorial guinea",
    c: "GNQ",
    d: "+240",
    f: "+240 ### ### ####",
    p: "+240 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gq.png",
    c_sm: "GQ",
  },
  {
    n: "Eritrea",
    c: "ERI",
    d: "+291",
    f: "+291 ### ### ####",
    p: "+291 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/er.png",
    c_sm: "ER",
  },
  {
    n: "Estonia",
    c: "EST",
    d: "+372",
    f: "+372 #### ######",
    p: "+372 7014 547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ee.png",
    c_sm: "EE",
  },
  {
    n: "Ethiopia",
    c: "ETH",
    d: "+251",
    f: "+251 ### ### ####",
    p: "+251 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/et.png",
    c_sm: "ET",
  },
  {
    n: "Finland",
    c: "FIN",
    d: "+358",
    f: "+358 ## ### ## ##",
    p: "+358 70 1454 77 33",
    fg: "http://flags.fmcdn.net/data/flags/mini/fi.png",
    c_sm: "FI",
  },
  {
    n: "France",
    c: "FRA",
    d: "+33",
    f: "+33 # ## ## ## ##",
    p: "+33 7 01 45 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/fr.png",
    c_sm: "FR",
  },
  {
    n: "French guiana",
    c: "GUF",
    d: "+594",
    f: "+594 ### ### ####",
    p: "+594 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gf.png",
    c_sm: "GF",
  },
  {
    n: "French polynesia",
    c: "PYF",
    d: "+689",
    f: "+689 ### ### ####",
    p: "+689 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pf.png",
    c_sm: "PF",
  },
  {
    n: "Gabon",
    c: "GAB",
    d: "+241",
    f: "+241 ### ### ####",
    p: "+241 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ga.png",
    c_sm: "GA",
  },
  {
    n: "Gambia",
    c: "GMB",
    d: "+220",
    f: "+220 ### ### ####",
    p: "+220 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gm.png",
    c_sm: "GM",
  },
  {
    n: "Georgia",
    c: "GEO",
    d: "+995",
    f: "+995 ### ### ####",
    p: "+995 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ge.png",
    c_sm: "GE",
  },
  {
    n: "Germany",
    c: "DEU",
    d: "+49",
    f: "+49 #### ########",
    p: "+49 7014 54773370",
    fg: "http://flags.fmcdn.net/data/flags/mini/de.png",
    c_sm: "DE",
  },
  {
    n: "Ghana",
    c: "GHA",
    d: "+233",
    f: "+233 ### ### ####",
    p: "+233 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gh.png",
    c_sm: "GH",
  },
  {
    n: "Greece",
    c: "GRC",
    d: "+30",
    f: "+30 ### ### ####",
    p: "+30 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gr.png",
    c_sm: "GR",
  },
  {
    n: "Grenada",
    c: "GRD",
    d: "+1473",
    f: "+1473 ### ### ####",
    p: "+1473 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gd.png",
    c_sm: "GD",
  },
  {
    n: "Guadeloupe",
    c: "GLP",
    d: "+590",
    f: "+590 ### ### ####",
    p: "+590 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gp.png",
    c_sm: "GP",
  },
  {
    n: "Guam",
    c: "GUM",
    d: "+1671",
    f: "+1671 ### ### ####",
    p: "+1671 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gu.png",
    c_sm: "GU",
  },
  {
    n: "Guatemala",
    c: "GTM",
    d: "+502",
    f: "+502 ####-####",
    p: "+502 7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/gt.png",
    c_sm: "GT",
  },
  {
    n: "Guinea",
    c: "GIN",
    d: "+224",
    f: "+224 ### ### ####",
    p: "+224 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gn.png",
    c_sm: "GN",
  },
  {
    n: "Guinea-bissau",
    c: "GNB",
    d: "+245",
    f: "+245 ### ### ####",
    p: "+245 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gw.png",
    c_sm: "GW",
  },
  {
    n: "Guyana",
    c: "GUY",
    d: "+592",
    f: "+592 ### ### ####",
    p: "+592 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gy.png",
    c_sm: "GY",
  },
  {
    n: "Haiti",
    c: "HTI",
    d: "+509",
    f: "+509 ####-####",
    p: "+509 7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/ht.png",
    c_sm: "HT",
  },
  {
    n: "Honduras",
    c: "HND",
    d: "+504",
    f: "+504 ### ### ####",
    p: "+504 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/hn.png",
    c_sm: "HN",
  },
  {
    n: "Hong kong",
    c: "HKG",
    d: "+852",
    f: "+852 #### ####",
    p: "+852 7014 5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/hk.png",
    c_sm: "HK",
  },
  {
    n: "Hungary",
    c: "HUN",
    d: "+36",
    f: "+36 ### ### ###",
    p: "+36 701 454 773",
    fg: "http://flags.fmcdn.net/data/flags/mini/hu.png",
    c_sm: "HU",
  },
  {
    n: "Iceland",
    c: "ISL",
    d: "+354",
    f: "+354 ### ####",
    p: "+354 701 4547",
    fg: "http://flags.fmcdn.net/data/flags/mini/is.png",
    c_sm: "IS",
  },
  {
    n: "India",
    c: "IND",
    d: "+91",
    f: "+91 ####-######",
    p: "+91 7014-547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/in.png",
    c_sm: "IN",
  },
  {
    n: "Indonesia",
    c: "IDN",
    d: "+62",
    f: "+62 ### ### ####",
    p: "+62 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/id.png",
    c_sm: "ID",
  },
  {
    n: "Iran",
    c: "IRN",
    d: "+98",
    f: "+98 ### ### ####",
    p: "+98 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ir.png",
    c_sm: "IR",
  },
  {
    n: "Iraq",
    c: "IRQ",
    d: "+964",
    f: "+964 ### ### ####",
    p: "+964 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/iq.png",
    c_sm: "IQ",
  },
  {
    n: "Ireland",
    c: "IRL",
    d: "+353",
    f: "+353 ## #######",
    p: "+353 70 1454773",
    fg: "http://flags.fmcdn.net/data/flags/mini/ie.png",
    c_sm: "IE",
  },
  {
    n: "Israel",
    c: "ISR",
    d: "+972",
    f: "+972 ### ### ####",
    p: "+972 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/il.png",
    c_sm: "IL",
  },
  {
    n: "Italy",
    c: "ITA",
    d: "+39",
    f: "+39 ### #######",
    p: "+39 701 4547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/it.png",
    c_sm: "IT",
  },
  {
    n: "Jamaica",
    c: "JAM",
    d: "+1876",
    f: "+1876 ### ### ####",
    p: "+1876 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/jm.png",
    c_sm: "JM",
  },
  {
    n: "Japan",
    c: "JPN",
    d: "+81",
    f: "+81 ## #### ####",
    p: "+81 70 1454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/jp.png",
    c_sm: "JP",
  },
  {
    n: "Jordan",
    c: "JOR",
    d: "+962",
    f: "+962 ### ### ####",
    p: "+962 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/jo.png",
    c_sm: "JO",
  },
  {
    n: "Kazakhstan",
    c: "KAZ",
    d: "+997",
    f: "+997 ### ###-##-##",
    p: "+997 701 454-77-33",
    fg: "http://flags.fmcdn.net/data/flags/mini/kz.png",
    c_sm: "KZ",
  },
  {
    n: "Kenya",
    c: "KEN",
    d: "+254",
    f: "+254 ### ### ####",
    p: "+254 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ke.png",
    c_sm: "KE",
  },
  {
    n: "Kiribati",
    c: "KIR",
    d: "+686",
    f: "+686 ### ### ####",
    p: "+686 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ki.png",
    c_sm: "KI",
  },
  {
    n: "Kosovo",
    c: "XKX",
    d: "+383",
    f: "+383 ### ### ####",
    p: "+383 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/xk.png",
    c_sm: "XK",
  },
  {
    n: "Kuwait",
    c: "KWT",
    d: "+965",
    f: "+965 ### ### ####",
    p: "+965 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/kw.png",
    c_sm: "KW",
  },
  {
    n: "Kyrgyzstan",
    c: "KGZ",
    d: "+996",
    f: "+996 ### ### ###",
    p: "+996 701 454 773",
    fg: "http://flags.fmcdn.net/data/flags/mini/kg.png",
    c_sm: "KG",
  },
  {
    n: "Laos",
    c: "LAO",
    d: "+856",
    f: "+856 ### ### ####",
    p: "+856 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/la.png",
    c_sm: "LA",
  },
  {
    n: "Latvia",
    c: "LVA",
    d: "+371",
    f: "+371 ## ## ###",
    p: "+371 70 14 547",
    fg: "http://flags.fmcdn.net/data/flags/mini/lv.png",
    c_sm: "LV",
  },
  {
    n: "Lebanon",
    c: "LBN",
    d: "+961",
    f: "+961 ### ### ####",
    p: "+961 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lb.png",
    c_sm: "LB",
  },
  {
    n: "Lesotho",
    c: "LSO",
    d: "+266",
    f: "+266 ### ### ####",
    p: "+266 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ls.png",
    c_sm: "LS",
  },
  {
    n: "Liberia",
    c: "LBR",
    d: "+231",
    f: "+231 ### ### ####",
    p: "+231 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lr.png",
    c_sm: "LR",
  },
  {
    n: "Libya",
    c: "LBY",
    d: "+218",
    f: "+218 ### ### ####",
    p: "+218 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ly.png",
    c_sm: "LY",
  },
  {
    n: "Liechtenstein",
    c: "LIE",
    d: "+423",
    f: "+423 ### ### ####",
    p: "+423 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/li.png",
    c_sm: "LI",
  },
  {
    n: "Lithuania",
    c: "LTU",
    d: "+370",
    f: "+370 ### ### ####",
    p: "+370 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lt.png",
    c_sm: "LT",
  },
  {
    n: "Luxembourg",
    c: "LUX",
    d: "+352",
    f: "+352 ### ### ####",
    p: "+352 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lu.png",
    c_sm: "LU",
  },
  {
    n: "Macau",
    c: "MAC",
    d: "+853",
    f: "+853 ### ### ####",
    p: "+853 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mo.png",
    c_sm: "MO",
  },
  {
    n: "Macedonia",
    c: "MKD",
    d: "+389",
    f: "+389 ### ### ####",
    p: "+389 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mk.png",
    c_sm: "MK",
  },
  {
    n: "Madagascar",
    c: "MDG",
    d: "+261",
    f: "+261 ### ### ####",
    p: "+261 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mg.png",
    c_sm: "MG",
  },
  {
    n: "Malawi",
    c: "MWI",
    d: "+265",
    f: "+265 ### ### ####",
    p: "+265 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mw.png",
    c_sm: "MW",
  },
  {
    n: "Malaysia",
    c: "MYS",
    d: "+60",
    f: "+60 ##-####-####",
    p: "+60 ##-7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/my.png",
    c_sm: "MY",
  },
  {
    n: "Maldives",
    c: "MDV",
    d: "+960",
    f: "+960 ### ### ####",
    p: "+960 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mv.png",
    c_sm: "MV",
  },
  {
    n: "Mali",
    c: "MLI",
    d: "+223",
    f: "+223 ### ### ####",
    p: "+223 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ml.png",
    c_sm: "ML",
  },
  {
    n: "Malta",
    c: "MLT",
    d: "+356",
    f: "+356 ### ### ####",
    p: "+356 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mt.png",
    c_sm: "MT",
  },
  {
    n: "Marshall islands",
    c: "MHL",
    d: "+692",
    f: "+692 ### ### ####",
    p: "+692 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mh.png",
    c_sm: "MH",
  },
  {
    n: "Martinique",
    c: "MTQ",
    d: "+596",
    f: "+596 ### ### ####",
    p: "+596 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mq.png",
    c_sm: "MQ",
  },
  {
    n: "Mauritania",
    c: "MRT",
    d: "+222",
    f: "+222 ### ### ####",
    p: "+222 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mr.png",
    c_sm: "MR",
  },
  {
    n: "Mauritius",
    c: "MUS",
    d: "+230",
    f: "+230 ### ### ####",
    p: "+230 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mu.png",
    c_sm: "MU",
  },
  {
    n: "Mexico",
    c: "MEX",
    d: "+52",
    f: "+52 ### ### ####",
    p: "+52 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mx.png",
    c_sm: "MX",
  },
  {
    n: "Micronesia",
    c: "FSM",
    d: "+691",
    f: "+691 ### ### ####",
    p: "+691 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/fm.png",
    c_sm: "FM",
  },
  {
    n: "Moldova",
    c: "MDA",
    d: "+373",
    f: "+373 (##) ##-##-##",
    p: "+373 (70) 14-54-77",
    fg: "http://flags.fmcdn.net/data/flags/mini/md.png",
    c_sm: "MD",
  },
  {
    n: "Monaco",
    c: "MCO",
    d: "+377",
    f: "+377 (###) ### ####",
    p: "+377 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mc.png",
    c_sm: "MC",
  },
  {
    n: "Mongolia",
    c: "MNG",
    d: "+976",
    f: "+976 (###) ### ####",
    p: "+976 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mn.png",
    c_sm: "MN",
  },
  {
    n: "Montenegro",
    c: "MNE",
    d: "+382",
    f: "+382 (###) ### ####",
    p: "+382 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/me.png",
    c_sm: "ME",
  },
  {
    n: "Montserrat",
    c: "MSR",
    d: "+1664",
    f: "+1664 (###) ### ####",
    p: "+1664 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ms.png",
    c_sm: "MS",
  },
  {
    n: "Morocco",
    c: "MAR",
    d: "+212",
    f: "+212 (###) ### ####",
    p: "+212 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ma.png",
    c_sm: "MA",
  },
  {
    n: "Mozambique",
    c: "MOZ",
    d: "+258",
    f: "+258 (###) ### ####",
    p: "+258 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mz.png",
    c_sm: "MZ",
  },
  {
    n: "Myanmar",
    c: "MMR",
    d: "+95",
    f: "+95 (###) ### ####",
    p: "+95 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/mm.png",
    c_sm: "MM",
  },
  {
    n: "Namibia",
    c: "NAM",
    d: "+264",
    f: "+264 (###) ### ####",
    p: "+264 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/na.png",
    c_sm: "NA",
  },
  {
    n: "Nauru",
    c: "NRU",
    d: "+674",
    f: "+674 (###) ### ####",
    p: "+674 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/nr.png",
    c_sm: "NR",
  },
  {
    n: "Nepal",
    c: "NPL",
    d: "+977",
    f: "+977 (###) ### ####",
    p: "+977 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/np.png",
    c_sm: "NP",
  },
  {
    n: "Netherlands",
    c: "NLD",
    d: "+31",
    f: "+31 ## ########",
    p: "+31 70 14547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/nl.png",
    c_sm: "NL",
  },
  {
    n: "New caledonia",
    c: "NCL",
    d: "+687",
    f: "+687 (###) ### ####",
    p: "+687 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/nc.png",
    c_sm: "NC",
  },
  {
    n: "New zealand",
    c: "NZL",
    d: "+64",
    f: "+64 ###-###-####",
    p: "+64 701-454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/nz.png",
    c_sm: "NZ",
  },
  {
    n: "Nicaragua",
    c: "NIC",
    d: "+505",
    f: "+505 (###) ### ####",
    p: "+505 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ni.png",
    c_sm: "NI",
  },
  {
    n: "Niger",
    c: "NER",
    d: "+227",
    f: "+227 (###) ### ####",
    p: "+227 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ne.png",
    c_sm: "NE",
  },
  {
    n: "Nigeria",
    c: "NGA",
    d: "+234",
    f: "+234 (###) ### ####",
    p: "+234 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ng.png",
    c_sm: "NG",
  },
  {
    n: "North korea",
    c: "PRK",
    d: "+850",
    f: "+850 (###) ### ####",
    p: "+850 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/kp.png",
    c_sm: "KP",
  },
  {
    n: "Norway",
    c: "NOR",
    d: "+47",
    f: "+47 ### ## ###",
    p: "+47 #70 14 547",
    fg: "http://flags.fmcdn.net/data/flags/mini/no.png",
    c_sm: "NO",
  },
  {
    n: "Oman",
    c: "OMN",
    d: "+968",
    f: "+968 (###) ### ####",
    p: "+968 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/om.png",
    c_sm: "OM",
  },
  {
    n: "Pakistan",
    c: "PAK",
    d: "+92",
    f: "+92 ###-#######",
    p: "+92 701-4547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pk.png",
    c_sm: "PK",
  },
  {
    n: "Palau",
    c: "PLW",
    d: "+680",
    f: "+680 (###) ### ####",
    p: "+680 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pw.png",
    c_sm: "PW",
  },
  {
    n: "Palestine",
    c: "PSE",
    d: "+970",
    f: "+970 (###) ### ####",
    p: "+970 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ps.png",
    c_sm: "PS",
  },
  {
    n: "Panama",
    c: "PAN",
    d: "+507",
    f: "+507 (###) ### ####",
    p: "+507 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pa.png",
    c_sm: "PA",
  },
  {
    n: "Papua new guinea",
    c: "PNG",
    d: "+675",
    f: "+675 (###) ### ####",
    p: "+675 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pg.png",
    c_sm: "PG",
  },
  {
    n: "Paraguay",
    c: "PRY",
    d: "+595",
    f: "+595 (###) ### ####",
    p: "+595 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/py.png",
    c_sm: "PY",
  },
  {
    n: "Peru",
    c: "PER",
    d: "+51",
    f: "+51 (###) ### ####",
    p: "+51 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pe.png",
    c_sm: "PE",
  },
  {
    n: "Philippines",
    c: "PHL",
    d: "+63",
    f: "+63 #### #######",
    p: "+63 7014 5477333",
    fg: "http://flags.fmcdn.net/data/flags/mini/ph.png",
    c_sm: "PH",
  },
  {
    n: "Poland",
    c: "POL",
    d: "+48",
    f: "+48 ###-###-###",
    p: "+48 701-454-773",
    fg: "http://flags.fmcdn.net/data/flags/mini/pl.png",
    c_sm: "PL",
  },
  {
    n: "Portugal",
    c: "PRT",
    d: "+351",
    f: "+351 (###) ### ####",
    p: "+351 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pt.png",
    c_sm: "PT",
  },
  {
    n: "Puerto rico",
    c: "PRI",
    d: "+1",
    f: "+1 (###) ### ####",
    p: "+1 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/pr.png",
    c_sm: "PR",
  },
  {
    n: "Qatar",
    c: "QAT",
    d: "+974",
    f: "+974 (###) ### ####",
    p: "+974 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/qa.png",
    c_sm: "QA",
  },
  {
    n: "Réunion",
    c: "REU",
    d: "+262",
    f: "+974 (###) ### ####",
    p: "+974 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/re.png",
    c_sm: "RE",
  },
  {
    n: "Romania",
    c: "ROU",
    d: "+40",
    f: "+40 (###) ### ####",
    p: "+40 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ro.png",
    c_sm: "RO",
  },
  {
    n: "Russia",
    c: "RUS",
    d: "+7",
    f: "+7 (###) ###-##-##",
    p: "+7 (701) 454-77-33",
    fg: "http://flags.fmcdn.net/data/flags/mini/ru.png",
    c_sm: "RU",
  },
  {
    n: "Rwanda",
    c: "RWA",
    d: "+250",
    f: "+250 (###) ### ####",
    p: "+250 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/rw.png",
    c_sm: "RW",
  },
  {
    n: "Saint kitts and nevis",
    c: "KNA",
    d: "+1869",
    f: "+1869 (###) ### ####",
    p: "+1869 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/kn.png",
    c_sm: "KN",
  },
  {
    n: "Saint lucia",
    c: "LCA",
    d: "+1758",
    f: "+1758 (###) ### ####",
    p: "+1758 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lc.png",
    c_sm: "LC",
  },
  {
    n: "Saint vincent and the grenadines",
    c: "VCT",
    d: "+1784",
    f: "+1784 (###) ### ####",
    p: "+1784 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/vc.png",
    c_sm: "VC",
  },
  {
    n: "Samoa",
    c: "WSM",
    d: "+685",
    f: "+685 (###) ### ####",
    p: "+685 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ws.png",
    c_sm: "WS",
  },
  {
    n: "San marino",
    c: "SMR",
    d: "+378",
    f: "+378 (###) ### ####",
    p: "+378 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sm.png",
    c_sm: "SM",
  },
  {
    n: "Sao tome and principe",
    c: "STP",
    d: "+239",
    f: "+239 (###) ### ####",
    p: "+239 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/st.png",
    c_sm: "ST",
  },
  {
    n: "Saudi arabia",
    c: "SAU",
    d: "+966",
    f: "+966 (###) ### ####",
    p: "+966 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sa.png",
    c_sm: "SA",
  },
  {
    n: "Senegal",
    c: "SEN",
    d: "+221",
    f: "+221 (###) ### ####",
    p: "+221 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sn.png",
    c_sm: "SN",
  },
  {
    n: "Serbia",
    c: "SRB",
    d: "+381",
    f: "+381 (###) ### ####",
    p: "+381 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/rs.png",
    c_sm: "RS",
  },
  {
    n: "Seychelles",
    c: "SYC",
    d: "+248",
    f: "+248 (###) ### ####",
    p: "+248 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sc.png",
    c_sm: "SC",
  },
  {
    n: "Sierra leone",
    c: "SLE",
    d: "+232",
    f: "+232 (###) ### ####",
    p: "+232 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sl.png",
    c_sm: "SL",
  },
  {
    n: "Singapore",
    c: "SGP",
    d: "+65",
    f: "+65 ####-####",
    p: "+65 7014-5477",
    fg: "http://flags.fmcdn.net/data/flags/mini/sg.png",
    c_sm: "SG",
  },
  {
    n: "Slovakia",
    c: "SVK",
    d: "+421",
    f: "+421 (###) ### ####",
    p: "+421 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sk.png",
    c_sm: "SK",
  },
  {
    n: "Slovenia",
    c: "SVN",
    d: "+386",
    f: "+386 (###) ### ####",
    p: "+386 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/si.png",
    c_sm: "SI",
  },
  {
    n: "Solomon islands",
    c: "SLB",
    d: "+677",
    f: "+677 (###) ### ####",
    p: "+677 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sb.png",
    c_sm: "SB",
  },
  {
    n: "Somalia",
    c: "SOM",
    d: "+677",
    f: "+677 (###) ### ####",
    p: "+677 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/so.png",
    c_sm: "SO",
  },
  {
    n: "South africa",
    c: "ZAF",
    d: "+27",
    f: "+27 (###) ### ####",
    p: "+27 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/za.png",
    c_sm: "ZA",
  },
  {
    n: "South korea",
    c: "KOR",
    d: "+82",
    f: "+82 ### #### ####",
    p: "+82 701 4547 7330",
    fg: "http://flags.fmcdn.net/data/flags/mini/kr.png",
    c_sm: "KR",
  },
  {
    n: "South sudan",
    c: "SSD",
    d: "+211",
    f: "+211 (###) ### ####",
    p: "+211 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ss.png",
    c_sm: "SS",
  },
  {
    n: "Spain",
    c: "ESP",
    d: "+34",
    f: "+34 ### ### ###",
    p: "+34 701 454 773",
    fg: "http://flags.fmcdn.net/data/flags/mini/es.png",
    c_sm: "ES",
  },
  {
    n: "Sri lanka",
    c: "LKA",
    d: "+94",
    f: "+94 ### ### ####",
    p: "+94 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/lk.png",
    c_sm: "LK",
  },
  {
    n: "Sudan",
    c: "SDN",
    d: "+249",
    f: "+249 ### ### ####",
    p: "+249 701 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sd.png",
    c_sm: "SD",
  },
  {
    n: "Suriname",
    c: "SUR",
    d: "+597",
    f: "+597 (###) ### ####",
    p: "+597 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sr.png",
    c_sm: "SR",
  },
  {
    n: "Sweden",
    c: "SWE",
    d: "+46",
    f: "+46 (###) ###-###",
    p: "+46 (701) 454-773",
    fg: "http://flags.fmcdn.net/data/flags/mini/se.png",
    c_sm: "SE",
  },
  {
    n: "Switzerland",
    c: "CHE",
    d: "+41",
    f: "+41 ## ### ## ##",
    p: "+41 70 145 77 33",
    fg: "http://flags.fmcdn.net/data/flags/mini/sz.png",
    c_sm: "SZ",
  },
  {
    n: "Syria",
    c: "SYR",
    d: "+963",
    f: "+963 (###) ### ####",
    p: "+963 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/sy.png",
    c_sm: "SY",
  },
  {
    n: "Taiwan",
    c: "TWN",
    d: "+886",
    f: "+886 (###) ### ####",
    p: "+886 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tw.png",
    c_sm: "TW",
  },
  {
    n: "Tajikistan",
    c: "TJK	",
    d: "+992",
    f: "+992 (###) ### ####",
    p: "+992 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tj.png",
    c_sm: "TJ",
  },
  {
    n: "Tanzania",
    c: "TZA",
    d: "+255",
    f: "+255 (###) ### ####",
    p: "+255 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tz.png",
    c_sm: "TZ",
  },
  {
    n: "Thailand",
    c: "THA",
    d: "+66",
    f: "+66 (###) ### ####",
    p: "+66 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/th.png",
    c_sm: "TH",
  },
  {
    n: "Timor-leste",
    c: "TLS",
    d: "+670",
    f: "+670 (###) ### ####",
    p: "+670 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tl.png",
    c_sm: "TL",
  },
  {
    n: "Togo",
    c: "TGO",
    d: "+228",
    f: "+228 (###) ### ####",
    p: "+228 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tg.png",
    c_sm: "TG",
  },
  {
    n: "Tonga",
    c: "TON",
    d: "+676",
    f: "+676 (###) ### ####",
    p: "+676 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/to.png",
    c_sm: "TO",
  },
  {
    n: "Trinidad and tobago",
    c: "TTO",
    d: "+1868",
    f: "+1868 (###) ### ####",
    p: "+1868 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tt.png",
    c_sm: "TT",
  },
  {
    n: "Tunisia",
    c: "TUN",
    d: "+216",
    f: "+216 (###) ### ####",
    p: "+216 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tn.png",
    c_sm: "TN",
  },
  {
    n: "Turkey",
    c: "TUR",
    d: "+90",
    f: "+90 ### ### ## ##",
    p: "+90 #70 145 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/tr.png",
    c_sm: "TR",
  },
  {
    n: "Turkmenistan",
    c: "TKM",
    d: "+993",
    f: "+993 (###) ### ####",
    p: "+993 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tm.png",
    c_sm: "TM",
  },
  {
    n: "Tuvalu",
    c: "TUV",
    d: "+688",
    f: "+688 (###) ### ####",
    p: "+688 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/tv.png",
    c_sm: "TV",
  },
  {
    n: "U.S. Virgin Islands",
    c: "VIR",
    d: "+1340",
    f: "+1340 (###) ### ####",
    p: "+1340 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/vi.png",
    c_sm: "VI",
  },
  {
    n: "Uganda",
    c: "UGA",
    d: "+256",
    f: "+256 (###) ### ####",
    p: "+256 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ug.png",
    c_sm: "UG",
  },
  {
    n: "Ukraine",
    c: "UKR",
    d: "+380",
    f: "+380 (##) ### ## ##",
    p: "+380 (70) 145 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/ua.png",
    c_sm: "UA",
  },
  {
    n: "United arab emirates",
    c: "ARE",
    d: "+971",
    f: "+971 (###) ### ####",
    p: "+971 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ae.png",
    c_sm: "AE",
  },
  {
    n: "United kingdom",
    c: "GBR",
    d: "+44",
    f: "+44 #### ######",
    p: "+44 7014 547733",
    fg: "http://flags.fmcdn.net/data/flags/mini/gb.png",
    c_sm: "GB",
  },
  {
    n: "United states",
    c: "USA",
    d: "+1",
    f: "+1 (###) ###-####",
    p: "+1 (701) 454-7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/us.png",
    c_sm: "US",
  },
  {
    n: "Uruguay",
    c: "URY",
    d: "+598",
    f: "+598 (###) ### ####",
    p: "+598 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/uy.png",
    c_sm: "UY",
  },
  {
    n: "Uzbekistan",
    c: "UZB",
    d: "+998",
    f: "+998 ## ### ## ##",
    p: "+998 70 145 47 73",
    fg: "http://flags.fmcdn.net/data/flags/mini/uz.png",
    c_sm: "UZ",
  },
  {
    n: "Vanuatu",
    c: "VUT",
    d: "+678",
    f: "+678 (###) ### ####",
    p: "+678 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/vu.png",
    c_sm: "VU",
  },
  {
    n: "Vatican",
    c: "VAT",
    d: "+379",
    f: "+379 ## #### ####",
    p: "+379 70 1454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/va.png",
    c_sm: "VA",
  },
  {
    n: "Venezuela",
    c: "VEN",
    d: "+58",
    f: "+58 (###) ### ####",
    p: "+58 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ve.png",
    c_sm: "VE",
  },
  {
    n: "Vietnam",
    c: "VNM",
    d: "+84",
    f: "+84 (###) ### ####",
    p: "+84 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/vn.png",
    c_sm: "VN",
  },
  {
    n: "Yemen",
    c: "YEM",
    d: "+967",
    f: "+967 (###) ### ####",
    p: "+967 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/ye.png",
    c_sm: "YE",
  },
  {
    n: "Zambia",
    c: "ZMB",
    d: "+260",
    f: "+260 (###) ### ####",
    p: "+260 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/zm.png",
    c_sm: "ZM",
  },
  {
    n: "Zimbabwe",
    c: "ZWE",
    d: "+263",
    f: "+263 (###) ### ####",
    p: "+263 (701) 454 7733",
    fg: "http://flags.fmcdn.net/data/flags/mini/zw.png",
    c_sm: "ZW",
  },
] as ICountryList[];
